services:
  mysql:
    image: mysql
    restart: always
    env_file: ./environment
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./environment
    depends_on:
      - mysql
    ports:
      - ${PORT}:${PORT}
